language: php

sudo: false

matrix:
  include:
    - php: '5.2'
      env: WP_VERSION=master WP_MULTISITE=1 PHPLINT=1 CODE_CLIMATE=1 CODECLIMATE_REPO_TOKEN=33af926f948ae958e14a3ecdc85c24e16a42a91f2a57a9c59bfb118c71a971e2
      dist: precise
    - php: '5.5'
      env: WP_VERSION=master WP_MULTISITE=0 PHPLINT=1
    - php: '5.5'
      env: WP_VERSION=4.0 WP_MULTISITE=1
    - php: '5.4'
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: '5.4'
      env: WP_VERSION=4.0 WP_MULTISITE=1
    - php: '5.5'
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: "5.5"
      env: WP_VERSION=3.9 WP_MULTISITE=1
    - php: "5.3"
      env: WP_VERSION=3.9 WP_MULTISITE=0

before_script:
- bash tests/bin/before.sh $WP_VERSION

script:
- if [[ "$PHPLINT" == "1" ]]; then bash tests/bin/phplint.sh; fi
- if [[ "$CODE_CLIMATE" == "1" ]]; then bash tests/bin/code_climate.sh; fi
