os: linux
dist: xenial
language: php

services:
  - mysql

cache:
  directories:
    - .cache
    - $HOME/.composer/cache

branches:
  only:
    - master
    - develop
    - /^release\/\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^hotfix\/\d+\.\d+(\.\d+)?(-\S*)?$/

jobs:
  fast_finish: true
  include:
    - php: 7.3
      env: WP_VERSION=master WP_MULTISITE=1 PHPCS=1
    - php: 7.2
      env: WP_VERSION=5.4 WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=5.5 WP_MULTISITE=0
    - php: 5.6
      env: PHPLINT=1 WP_VERSION=5.4 WP_MULTISITE=1
    - php: 7.4
      env: PHPLINT=1 WP_VERSION=5.5 WP_MULTISITE=0
    - php: "nightly"
      env: PHPLINT=1

  allow_failures:
    # Allow failures for unstable builds.
    - php: "nightly"

before_install:
- composer self-update 1.10.16
- export WP_DEVELOP_DIR=/tmp/wordpress/

install:
- |
  if [[ $TRAVIS_PHP_VERSION == "nightly" ]]; then
    composer install --no-interaction --ignore-platform-reqs
  else
    composer install --no-interaction
  fi

before_script:
- |
  if [[ $TRAVIS_PHP_VERSION != "nightly" ]]; then
    bash tests/bin/before.sh $WP_VERSION
  fi

script:
- if [[ "$PHPLINT" == "1" ]]; then composer lint; fi
- if [[ "$PHPCS" == "1" ]]; then composer check-cs; fi
- |
  if [[ $TRAVIS_PHP_VERSION != "nightly" ]]; then
    composer test
  fi

# Validate the composer.json file.
# @link https://getcomposer.org/doc/03-cli.md#validate
- if [[ $TRAVIS_PHP_VERSION == "5.6" || $TRAVIS_PHP_VERSION == "7.4" ]]; then composer validate --no-check-all; fi

